"""Shared layout constants for podkład xlsx read/write."""

from __future__ import annotations

# RANO / POPOŁUDNIE color markers live on these rows (Excel 1-based).
MORNING_COLOR_ROW = 9
MORNING_INTERVAL_ROW = 10
AFTERNOON_COLOR_ROW = 11
AFTERNOON_INTERVAL_ROW = 12
FLEXIBLE_COLOR_ROW = 13
FLEXIBLE_INTERVAL_ROW = 14
CUSTOM_INTERVAL_COLOR_ROW = 15
CUSTOM_INTERVAL_VALUE_ROW = 16

DEFAULT_MORNING_RANGE = ("08:00", "15:15")
DEFAULT_AFTERNOON_RANGE = ("15:00", "22:00")
DEFAULT_FULL_DAY_RANGE = ("08:00", "22:00")

NAME_HEADER_ROW_SCAN_LIMIT = 20
