create table if not exists public."Shift_templates" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name character varying not null,
  shifts jsonb not null default '[]'::jsonb,
  constraint Shift_templates_pkey primary key (id)
) tablespace pg_default;
